name: Changelog Bot

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - CHANGELOG.md

permissions: {}

jobs:
  changelog-bot:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      - name: Update Changelog
        uses: ponylang/changelog-bot-action@082ec1b28d0c0e634155d0933528a8b44bdfcafa # 0.3.3
        with:
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
