name: PR

on: pull_request

permissions:
  contents: read

jobs:
  lint-entrypoint-py:
    name: Lint entrypoint.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: pylint
        run: make pylint

  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3@sha256:11ec9aa31cdcb296de042942b18bb2c1a00495775657eb3b68c271f79ba1e86c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  validate-docker-image-builds:
    name: Validate Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Docker build
        run: make build

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release@sha256:fc9aa9546bf1fb669eb956fb7c4ec63f53bf065da748ddaf4fbaa04971d6ebd4
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Verify CHANGELOG
        run: changelog-tool verify
