name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

permissions: {}

jobs:
  update-version-in-readme-examples:
    runs-on: ubuntu-latest
    name: Update version in README examples
    steps:
      - name: Update version in README examples
        uses: ponylang/action-readme-version-updater@200c5c4d881a315f7a41a49bb4643a7a8021eed5 # 0.1.3
        with:
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          API_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs: [update-version-in-readme-examples]
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Trigger
        uses: ponylang/release-bot-action@34efa6656c60a3075ef39a9861ee105a5d8ac42f # 0.5.0
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
