name: Release Notes Reminder

on:
  pull_request_target:
    types:
      - labeled

permissions: {}

jobs:
  release-note-reminder:
    runs-on: ubuntu-latest
    name: Prompt to add release notes
    steps:
      - name: Prompt to add release notes
        uses: ponylang/release-notes-reminder-bot-action@60b0f3c7f4601925362ea4057aeb66d7410ac32e # 0.1.0
        env:
          API_CREDENTIALS: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
